### ISSUE TITLE
when using pnpm and `publishConfig.directory` publish errors out

### ISSUE THREAD

**Issue by Tirke** [changesets/changesets#773] opened 2022-03-07 15:57 UTC
## Affected Packages

I guess [cli/publish](https://github.com/changesets/changesets/tree/main/packages/cli/src/commands/publish)

## Problem

I'm in a `nx` monorepo with a `pnpm` workspace. `nx` is configured to build in a dist dir at the root of the monorepo.
When specifying `publishConfig.directory` in the `package.json` the code of `changesets` will get the correct directory but then following [`pnpm` doc](https://pnpm.io/package_json#publishconfigdirectory), `pnpm` will interpret the path again leading to a bad path (in my case I end up with one part of the path doubled).

Removing the field `publishConfig.directory` from the `package.json` in the dist dir fix the issues.

## Proposed solution

🤷 Maybe we could remove the `publishConfig.directory` field to prevent `pnpm` from interpreting it but it's a bit involved.

**Comment by Andarist** [comment] 2022-03-07 16:15
Could you list the exact steps taken by different tools involved in the process? How a package directory looks before & after each tool gets executed in the pipeline?

**Comment by Tirke** [comment] 2022-03-08 08:06
@Andarist Sure.


Some of the code in the monorepo
`package.json` root package.json
`packages/package/package.json` package.json of the package to be published with a publish config 
```json
"publishConfig": {
    "directory": "../../dist/packages/tmp"
  }
```
`packages/package/project.json` nx config file for the package
`packages/package/src/*`

I can now run `changeset version` if I have any changesets.

Then I run `nx package:build`

I end up with the `dist` dir at the root of the monorepo containing the build of my package

`dist/packages/package/package.json`
`dist/packages/package/CHANGELOG.md`
`dist/packages/package/README.md`
`dist/packages/package/src/index.js`
...


Then if I run `changeset publish` changeset pickups the `publishConfig` in the `packages/package/package.json` package.json and then runs `pnpm publish` inside the dist directory where `pnpm` pick ups the `publishConfig` inside the `dist/packages/package/package.json` package.json.

**Comment by Andarist** [comment] 2022-03-08 10:27
Hmm, so I wonder what we could really do about this here. It really seems that Changesets is not involved in the process all of that much - we just invoke `pnpm publish` in the given directory and that's all. And you need us to do this because that `publishConfig.directory` is where build artifacts are and those should be published.

I think the problem is in the packing stage of this workflow - so within Nx itself, I don't see how to solve this without removing `publishConfig.directory` from this dist directory. It feels like this kind of setup would always suffer from this issue - having Changesets in the mix doesn't make it pop up, it would always be present for monorepos using Nx + `publishConfig.directory` + pnpm. So I think that this should be addressed in Nx.

Do you have a link to the docs for the `publishConfig.directory` in Nx? I can't quite find it

**Comment by Tirke** [comment] 2022-03-08 10:31
There is no link to `nx`.
`changeset` is reading `publishConfig.directory` to know where it should call `pnpm publish` which then also read `publishConfig.directory`. 
The only thing related to `nx` is that i decide to build my packages in a root `dist` directory but that can happen with any build tool (and it's the case here, at the end it's only nx that's telling `swc` to build where I want it to build.
I could have a monorepo without nx and just `webpack` / any other build tool  that build in a `dist` folder of my choice.

**Comment by Andarist** [comment] 2022-03-08 11:46
Hmm... so I guess what you are saying is that we shouldn't handle `publishConfig.directory` on our own when using pnpm and let it resolve it on its own.

So it would read the `packages/package/package.json#publishConfig.directory`, use the target directory as something that needs to be published but it would ignore the `dist/packages/package/package.json#publishConfig.directory` in such a situation?

**Comment by Tirke** [comment] 2022-03-08 15:30
Yeah I think that's it. Thinking a bit more about it, it's just pnpm who needs to know where to run its `publish` command. So if we just had a way for `changeset` to known where to run `pnpm publish` that **isn't** `publishConfig.directory` it should solve the problem :)

**Comment by Andarist** [comment] 2022-03-08 17:09
> Yeah I think that's it. 

Have you confirmed (perhaps by patching Changesets) that it would work for you?

> Do note that it's a bit different from letting pnpm handle it.

Hmm, I'm rereading this and I'm somewhat unsure how this is different. Could you clarify? Both read roughly in the same way to me.

**Comment by Tirke** [comment] 2022-03-10 08:02
Sorry for the late answer. 
The only problem for me is that both `changesets` and `pnpm` interpret the same config key (`publishConfig.directory`) 
This is the interesting code for me: https://github.com/changesets/changesets/blob/a3fa3ece513f96f3e2ce1fb1f228e450e40cbdd2/packages/cli/src/commands/publish/publishPackages.ts#L129-L141

I want `changesets` to run in the directory I care about, what happens after is purely a side effect for me, I really don't want pnpm to interpret directory again because `changesets` is already `cwding` pnpm in the correct dir.

**Comment by Tirke** [comment] 2022-03-24 15:37
@Andarist sorry to bother you but is it more clear from your side?

**Closed** 2023-10-10 21:52 UTC
