### ISSUE TITLE
[suggestion] how about adding a static documention-site such with Docusaurus or Vuepress

### ISSUE THREAD

**Issue by SoonIter** [changesets/changesets#1061] opened 2023-01-18 07:58 UTC
## Affected Packages
no package

## Problem
🤔I wanna know what makes changesets provide no documention site, cost too much or something else.

As the title, I think the documention has restricted the progress of changesets so that a lot of people didn't realize how useful this tool is.

In the past, document changes are also frequent and easy to make a mistake and I think to build a site with Docusaurus is a good choice.

Maybe community can offer some help

## Proposed solution
I can format the documention as other projects, maybe need a lot of code review.

**Comment by Andarist** [comment] 2023-01-18 08:23
I would gladly accept a PR that would setup the docs.

**Comment by bluwy** [comment] 2024-10-06 08:32
Marking as duplicate of https://github.com/changesets/changesets/issues/1134 (this issue is opened first, but it looks like there's more activity going on at the other issue)

**Closed by bluwy** 2024-10-06 08:32 UTC
