### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'dependents')

### ISSUE THREAD

**Issue by kingzez** [changesets/changesets#1217] opened 2023-08-21 06:11 UTC
## Affected Packages

 `@changesets/get-dependents-graph` 

use `"@changesets/cli": "^2.26.2",`
```
# .npmrc
shared-workspace-lockfile=false
auto-install-peers=true
ignore-scripts=false
strict-peer-dependencies=false
```

pnpm workspace exists project, when pnpm@7 upgrade to pnpm@8  pnpm-lock lockfileVersion from 5.4 to 6,
and run changeset, occur follow error

## Problem

```bash
> pnpm changeset

🦋  error TypeError: Cannot read properties of undefined (reading 'dependents')
🦋  error     at /Users/project/node_modules/.pnpm/@changesets+get-dependents-graph@1.3.6/node_modules/@changesets/get-dependents-graph/dist/get-dependents-graph.cjs.dev.js:138:38
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at /Users/project/node_modules/.pnpm/@changesets+get-dependents-graph@1.3.6/node_modules/@changesets/get-dependents-graph/dist/get-dependents-graph.cjs.dev.js:137:20
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at Object.getDependentsGraph (/Users/project/node_modules/.pnpm/@changesets+get-dependents-graph@1.3.6/node_modules/@changesets/get-dependents-graph/dist/get-dependents-graph.cjs.dev.js:131:21)
🦋  error     at parse (/Users/project/node_modules/.pnpm/@changesets+config@2.3.1/node_modules/@changesets/config/dist/config.cjs.dev.js:224:50)
🦋  error     at Object.read (/Users/project/node_modules/.pnpm/@changesets+config@2.3.1/node_modules/@changesets/config/dist/config.cjs.dev.js:107:10)
🦋  error     at async run$2 (/Users/project/node_modules/.pnpm/@changesets+cli@2.26.2/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1313:16)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by kherock** [comment] 2023-11-24 18:00
I encountered this issue recently as well - adding `.` also worked around the issue for my Yarn workspaces.

**Comment by samijaber** [comment] 2023-11-30 16:25
I had this in a yarn v3 mono-repo. Turns out I had setup changesets in a sub-folder of my monorepo. I fixed it by running `changesets init` in the real root of my mono-repo.

**Comment by bluwy** [comment] 2024-10-05 16:59
Duplicate of https://github.com/changesets/changesets/issues/1133 (preferring that issue as it's opened first)

**Closed by bluwy** 2024-10-05 16:59 UTC
