### ISSUE TITLE
Changes not detected by changeset cli 2.23.1

### ISSUE THREAD

**Issue by danielgangverk** [changesets/changesets#869] opened 2022-07-12 14:17 UTC
## Affected Packages

@changesets/cli: 2.23.1

## Problem

When running `changeset` in the cli after having made changes in a package, no changes are detected. That is, all packages are listed as unchanged.
<img width="839" alt="image" src="https://user-images.githubusercontent.com/76997398/178507904-e39fce95-53e8-4274-936a-c74715ac4b41.png">

When running the same command in version 2.22.0, the changes are detected and the package is suggested in the cli.

**Config**
```json
{
  "$schema": "https://unpkg.com/@changesets/config@2.0.0/schema.json",
  "changelog": ["@changesets/changelog-github", { "repo": "PRIVATE_REPO" }],
  "commit": false,
  "fixed": [],
  "linked": [],
  "access": "restricted",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```

**Comment by slinkardbrandon** [comment] 2022-07-13 15:41
I am having this same issue, its interesting because `changeset status` still works, but the add command isn't detecting properly for some reason.

> $ changeset status --since=main                                                                                                                                                                                                                                 
   🦋  error Some packages have been changed but no changesets were found. Run `changeset add` to resolve this error.
   🦋  error If this change doesn't need a release, run `changeset add --empty`.

> $ changeset add                                                                                                                                                                                                                                               
  🦋  Which packages would you like to include? … 
    ◯ unchanged packages

**Comment by glasser** [comment] 2022-07-13 17:29
I'm seeing this too. Note that it's specifically 2.23.1 that causes the issue (2.23.0 is fine). Sees likely that #744 is to blame? Probably this line: https://github.com/changesets/changesets/pull/744/files#r920335959

**Comment by Andarist** [comment] 2022-07-13 20:44
I believe that has been fixed by https://github.com/changesets/changesets/releases/tag/%40changesets%2Fcli%402.23.2 .

**Comment by BarryThePenguin** [comment] 2022-07-21 03:17
I had the same problem, came here and found this issue, updated to 2.23.2 and it looks like that fixed the problem. Thanks! 🎉

**Comment by Andarist** [comment] 2022-07-21 07:54
This was a problem only briefly and got fixed in 2.23.2

**Closed** 2022-07-21 07:54 UTC

**Comment by buquan** [comment] 2023-02-14 00:55
> This was a problem only briefly and got fixed in 2.23.2

<img width="644" alt="image" src="https://user-images.githubusercontent.com/23711051/218610019-0def5d89-3a1b-4446-a108-919d39f515cd.png">
why  cant i get 2.23.2, need you reply, thanks

**Comment by buquan** [comment] 2023-02-14 00:57
> This was a problem only briefly and got fixed in 2.23.2

it appeared again at 2.26, need your reply, thanks

**Comment by Andarist** [comment] 2023-02-14 10:01
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by buquan** [comment] 2023-02-14 10:03
> Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given

ok i would create demo in codesandbox recently thanks alot

**Comment by christopher-francisco** [comment] 2023-04-18 11:21
@buquan we're seeing the same issue. Wondering if you were able to create the codesandbox?

**Comment by rossipedia** [comment] 2023-07-09 19:23
Hitting this also on `2.26.1`, I'll see if I can provide a git repo that reproduces the issue. I believe it's related to `devDependencies`
